import type { Metadata } from "next";
import "./globals.css";
import { Kanit } from "next/font/google"; // ฟอนต์
import "@fortawesome/fontawesome-free/css/all.css";


const kanit = Kanit({ weight: "500" });

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${kanit.className} antialiased`}>
                {children}
            </body>
        </html>
    );
}
