import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Kanit } from 'next/font/google'; // ฟอนต์
import '@fortawesome/fontawesome-free/css/all.css';
import Navbar from "./components/Navbar";

// const geistSans = Geist({
//     variable: "--font-geist-sans",
//     subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//     variable: "--font-geist-mono",
//     subsets: ["latin"],
// });

const kanit = Kanit({ weight: "500" })

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    
    return (
        <html lang="en">
            <body
                className={`${kanit.className} antialiased`}
            >
                {/* <Navbar/> */}
                
                
                
                {children}
            </body>
        </html>
    );
}
